FROM safarov/freeswitch:latest

ENV DEBIAN_FRONTEND=noninteractive

# Create recording & sound directories
RUN mkdir -p /var/lib/freeswitch/recordings /etc/freeswitch/tls

# Copy Custom FreeSWITCH Configuration
COPY config/freeswitch/ /etc/freeswitch/

EXPOSE 5060/udp 5060/tcp 5080/udp 5080/tcp 7443/tcp 8021/tcp 16384-32768/udp

CMD ["freeswitch", "-nc", "-nonat"]

